file_root = "\\boot"
kernel_file = "kernel.bin"
font_file = "kernel-font.ttf"
dwarf_file = "dwarf.baker"
packed_file = "drivers.pak"
screen_resolution = { width = 1920, height = 1080 }
any_key_boot = false 
early_boot_kernel_page_table_page_count = 64 # 64 Pages for kernel elf 

[kernel_config]
font_size = 14
log_level = 1

