file_root = "\\boot"
kernel_file = "kernel.bin"
font_file = "kernel-font.ttf"
dwarf_file = "dwarf.baker"
screen_resolution = { width = 1920, height = 1080 }
any_key_boot = false

[kernel_config]
font_size = 15
