[package]
name = "build-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = { version = "3.6.1", features = ["wayland-data-control"] }
portable-pty = "0.9.0"
ratatui = "0.30.0"
thiserror = "2.0.17"
toml = "0.9.10"
