[package]
name = "baker"
version = "0.1.0"
edition = "2024"
description = "Baked dwarf information into a single file"

[dependencies]
object = "0.32"
addr2line = "0.21"
gimli = "0.27" 
rustc-demangle = "0.1"
bakery = { path = "../bakery" }
